### ISSUE TITLE
Publish source-code

### ISSUE THREAD

**Issue by iamwavecut** [robert-hoffmann/PowerToys4OpenAI#8]
Please share the source code of the CRX itself

**Comment by robert-hoffmann** [comment]
I will do this when the code is stable, so i don't have to bend over backwards when doing merges (i hate merges ^^)

Right now the code is still highly fluctuating, as i keep refactoring stuff all over the place and add documentation as i go along.

Thank you for the Russian language 🙏
I will try to stabilize what i'm doing right now, and maybe get that out in a week or so (... between my full-time job) 👍

**Comment by robert-hoffmann** [comment]
I'll just keep this open for discussion

**Comment by geminigeek** [comment]
Only project I could find using quasar bex mode, I am also interested in seeing how it's done .

**Comment by robert-hoffmann** [comment]
Initial code has been cleaned up and published (working version)

I did try to update some quasar & other stuff, but didn't go as expected, so i published what works 👍

**Comment by robert-hoffmann** [comment]
yarn install
yarn build

Then go to chrome extensions, enable dev mode, and browse to the dist/bex folder, and load that

The new OpenAI api keys work, but you need to allow all ..not sure why a read-only key doesn't work
